import Projects from "./Projects";

export default function AllProjects() {
  const paidProjects = [
    {
      id: 1,
      title: "Sombrero Coffee Shop",
      img: "imgs/paid-projects/sombrero.png",
      alt: "sombrero website image",
      code: "https://github.com/Amermob/Sombrero-Coffee-Shop",
      link: "https://amermob.github.io/Sombrero-Coffee-Shop/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 2,
      title: "Sabahat Al Eid",
      img: "imgs/paid-projects/sabahat al eid.png",
      alt: "Sabahat al Eid Website image",
      code: "https://github.com/Amermob/Sabahat-al-Eid",
      link: "https://amermob.github.io/Sabahat-al-Eid/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 3,
      title: "Blue Arrow For Events",
      img: "imgs/paid-projects/blue-arrow.png",
      alt: "Blue Arrow Website image",
      code: "https://github.com/Amermob/blue-arrows",
      link: "https://amermob.github.io/blue-arrows/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
      react: "imgs/react.png",
    },
  ];
  const paidProjectsList = paidProjects.map((project) => {
    console.log(project.tech);
    return <Projects key={project.id} {...project} />;
  });

  const learningProjects = [
    {
      id: 4,
      title: "Tenzies Game",
      img: "imgs/learning-projects/tenzies-game.png",
      alt: "Tenzies Game Website image",
      code: "https://github.com/Amermob/Tenzies-game",
      link: "https://amermob.github.io/Tenzies-game/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
      react: "imgs/react.png",
    },
        {
      id: 5,
      title: "PSG E-commerce Website",
      img: "imgs/learning-projects/PSG.png",
      alt: "PSG E-commerce Website Website image",
      code: "https://github.com/Amermob/PS-Games",
      link: "https://psg-games.netlify.app",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
      react: "imgs/react.png",
    },
    
       {
      id: 6,
      title: "VanLife",
      img: "imgs/learning-projects/van.png",
      alt: "VanLife Website image",
      code: "https://github.com/Amermob/vanlife",
      link: "https://amermob.github.io/vans",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
      react: "imgs/react.png",
    },
    
    {
      id: 7,
      title: "Assembly:Endgame",
      img: "imgs/learning-projects/endgame.png",
      alt: "Assembly-Endgame Website image",
      code: "https://github.com/Amermob/Assembly-Endgame",
      link: "https://amermob.github.io/Assembly-Endgame/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
      react: "imgs/react.png",
    },
    {
      id: 8,
      title: "Quiz Game",
      img: "imgs/learning-projects/quiz.png",
      alt: "Quiz Game Website image",
      code: "https://github.com/Amermob/Quizzical",
      link: "https://amermob.github.io/Quizzical/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
      react: "imgs/react.png",
    },
    {
      id: 9,
      title: "Memes Generator",
      img: "imgs/learning-projects/meme-generator.png",
      alt: "Memes Generator Website image",
      code: "https://github.com/Amermob/meme-generator",
      link: "https://amermob.github.io/meme-generator/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
      react: "imgs/react.png",
    },
    {
      id: 10,
      title: "Dragon Ball Character",
      img: "imgs/learning-projects/dragon-ball-characters-with-api.png",
      alt: "Dragon Ball Character Website image",
      code: "https://github.com/Amermob/dragon-ball-character",
      link: "https://amermob.github.io/dragon-ball-character/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
      react: "imgs/react.png",
    },
    {
      id: 11,
      title: "Generate a Password",
      img: "imgs/learning-projects/password-generator.png",
      alt: "Generate a Random Password",
      code: "https://github.com/Amermob/Generate-a-random-password",
      link: "https://amermob.github.io/Generate-a-random-password/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 12,
      title: "Grocery List",
      img: "imgs/learning-projects/list.png",
      alt: "Grocery List Website image",
      code: "https://github.com/Amermob/grocery-list",
      link: "https://amermob.github.io/grocery-list/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 13,
      title: "Image Slider",
      img: "imgs/learning-projects/image-slider.png",
      alt: "Image Slider Website image",
      code: "https://github.com/Amermob/slider",
      link: "https://amermob.github.io/slider/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 14,
      title: "Background Video",
      img: "imgs/learning-projects/background-video.png",
      alt: "background-video-player Website image",
      code: "https://github.com/Amermob/background-video-player",
      link: "https://amermob.github.io/background-video-player/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 15,
      title: "Calculator",
      img: "imgs/learning-projects/calculator.png",
      alt: "Calculator Website image",
      code: "https://github.com/Amermob/calculator",
      link: "https://amermob.github.io/calculator/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 16,
      title: "GitHub User Repos",
      img: "imgs/learning-projects/repos.png",
      alt: "GitHub User Repos Website image",
      code: "https://github.com/Amermob/get-user-repositories",
      link: "https://amermob.github.io/get-user-repositories/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 17,
      title: "Unit Conversion",
      img: "imgs/learning-projects/calc-unit.png",
      alt: "Metric/Imperial Unit Conversion Website image",
      code: "https://github.com/Amermob/Metric-Imperial-Unit-Conversion",
      link: "https://amermob.github.io/Metric-Imperial-Unit-Conversion/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 18,
      title: "Pepe the Frog Mood",
      img: "imgs/learning-projects/pepe-the-frog.png",
      alt: "Pepe the Frog Website image",
      code: "https://github.com/Amermob/pepe-the-frog",
      link: "https://amermob.github.io/pepe-the-frog/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 19,
      title: "Twitter Clone for Cats",
      img: "imgs/learning-projects/twitter-clone-for-cats.png",
      alt: "PTwitter Clone for Cats Website image",
      code: "https://github.com/Amermob/twitter-clone-for-cat",
      link: "https://amermob.github.io/twitter-clone-for-cat/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 20,
      title: "Color Scheme",
      img: "imgs/learning-projects/color-cheme-with-api.png",
      alt: "Color Scheme with API Website image",
      code: "https://github.com/Amermob/color-scheme-using-api",
      link: "https://amermob.github.io/color-scheme-using-api/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
    {
      id: 21,
      title: "Card Game",
      img: "imgs/learning-projects/card-game.png",
      alt: "Card Game using with API Website image",
      code: "https://github.com/Amermob/game-card",
      link: "https://amermob.github.io/game-card/",
      html: "imgs/HTML.png",
      css: "imgs/CSS.png",
      js: "imgs/JS.png",
    },
  ];
  const learningProjectsList = learningProjects.map((project) => {
    return <Projects key={project.id} {...project} />;
  });
  return (
    <div className="container">
      <h3>*Paid Projects*</h3>
      <div id="projects" className="projects">
        {paidProjectsList}
      </div>
      <hr></hr>
      <h3>*Project-Based Learning*</h3>
      <div id="projects" className="projects">
        {learningProjectsList}
      </div>
    </div>
  );
}
